#version:

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      #- APPLE_CLIENT_ID=${APPLE_CLIENT_ID}
      #- APPLE_TEAM_ID=${APPLE_TEAM_ID}
      #- APPLE_KEY_ID=${APPLE_KEY_ID}
      #- APPLE_PRIVATE_KEY=${APPLE_PRIVATE_KEY}
      #- FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      #- FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
